### ISSUE TITLE
Java 11 support 

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/Enigma#103]
A few things need to be done to support J11

- [x] Update the syntax pane library to 1.2.0 to fix [Crash log](https://gist.github.com/modmuss50/66b374d929226fa327fc0182636c61cd) _Tested to work_

- [x] Fix the decompiler using URLClassPath [Crash log](https://gist.github.com/modmuss50/7e7ccdd0bb57a69672e48bcdfccac69d)

- [ ] Dracula causes warnings, [Link to issue](https://github.com/bulenkov/Darcula/issues/41)

Not the end of the world right now, but might be something to keep in mind. There may be more issues as well.

**Comment by Ansraer** [comment]
I am currently looking into making engima compatible with java 1.9 since the buggy dpi scaling in 1.8 makes enigma unuseable on a 4k monitor. 
I have run into a bit of a dead end right now since enigma uses a fork of Procyon-compiler tools (http://maven.modmuss50.me/org/bitbucket/mstrobel/procyon-compilertools/) that appears to be horribly out of date (a fix for the URLClassPath was committed to the original Procyon about a year ago). Could you please either upload your fork to a github repo or simply publish a updated version to your maven?

**Comment by modmuss50** [comment]
We can look into it, I know the compiler tools that I host has 1 patch (somewhere on bit bucket irrc)

**Comment by Ansraer** [comment]
Thanks, I would greatly appreciate that.

**Comment by asiekierka** [comment]
Maybe you should just migrate the Procyon repo to here, seeing as it's not really maintained.

MORE FORKS \o/

**Comment by modmuss50** [comment]
I think I have found the version of procyon we use,

https://bitbucket.org/cuchaz/procyon/commits/all

There are a number of commits from cuchaz that may or may not be relevant still.

**Comment by asiekierka** [comment]
That's actually quite outdated compared to mainline!

The only relevant commit for us is https://bitbucket.org/cuchaz/procyon/commits/a8cc9faf9b17bc4de56297c0873d6ab48f106d98 , I'm pretty sure. I'd just fork upstream to FabricMC and cherry-pick this, and hope it works.

**Comment by asiekierka** [comment]
Working on this.

**Comment by asiekierka** [comment]
There is an issue with Unsafe.defineClass being missing in Java 11+ specifically, but I'm pretty sure it does not affect Enigma, merely the standalone decompiler.
