### ISSUE TITLE
Local variables/parameter names are snowmen

### ISSUE THREAD

**Issue by KennyTV** [FabricMC/Enigma#303]
Decompiling the mapped client jar with procyon keeps all parameter names and local variables as `\u2603` (snowman emoji).

Commands I used:
```
java -cp enigma-cli.jar cuchaz.enigma.command.Main convert-mappings proguard client-1.16.2.txt enigma_file mapping
java -cp enigma-cli.jar cuchaz.enigma.command.Main decompile PROCYON client-1.16.2.jar sources mapping
```

Here's one such example:
```java
    public ClientChunkCache(final ClientLevel \u2603, final int \u2603) {
        this.level = \u2603;
        this.emptyChunk = new EmptyLevelChunk(\u2603, new ChunkPos(0, 0));
        this.lightEngine = new LevelLightEngine(this, true, \u2603.dimensionType().hasSkyLight());
        this.storage = new Storage(calculateStorageRange(\u2603));
    }
```
or `final int access$600 = this.storage.chunkRadius;`

**Comment by 2xsaiko** [comment]
Does this happen in the Enigma GUI and/or with CFR decompiler?

**Comment by KennyTV** [comment]
CFR doesn't actually seem able to finish decompiling.
The parameters/variables look fine when applying the mappings in the GUI tho (but when exporting in the GUI, the same bad names happen again) https://i.imgur.com/PyY7N0x.png 👀

**Comment by 2xsaiko** [comment]
Hmm, then I guess something else happens when exporting the source than when opening a class in the GUI, and that is missing some fixes to make it not export everything as snowmen? Which makes sense since iirc it implements decompilation separately and doesn't use the same code paths as the GUI.

**Comment by KennyTV** [comment]
This is the commit that broke it. https://github.com/FabricMC/Enigma/commit/f0885819aeeb2edbfcfc0b23566cccb571166a02

**Comment by 2xsaiko** [comment]
Hmm, @Runemoro any idea what might have happened in that commit to cause this?

**Comment by Runemoro** [comment]
Yes. The local variable fixes were moved from the Procyon-specific code to a new `LocalVariableFixVisitor` class, but this line wasn't updated: https://github.com/FabricMC/Enigma/blob/57af19a99b2c7358d78f102b91482b2073126881/enigma/src/main/java/cuchaz/enigma/EnigmaProject.java#L178 The node should be passed through `LocalVariableFixVisitor` as well.

There's many more problems with jar/source export, though, such as bridges not being remapped and local variable conflicts. I think we should switch to using tiny-remapper to remap the jar instead of using the broken Enigma translators.

**Comment by 2xsaiko** [comment]
I would, but I'm on vacation for another week :^)
