### ISSUE TITLE
Avoid expensive searches while entering a query

### ISSUE THREAD

**Issue by haykam821** [FabricMC/Enigma#384]
The search is performed despite the query not being fully entered, causing major performance issues if the incomplete query is a common part of a class, method, or field name.

**Comment by 2xsaiko** [comment]
What kind of issues do you mean?

**Comment by haykam821** [comment]
Performance. Typing a single character in any search will freeze Enigma for a long period of time.

**Comment by 2xsaiko** [comment]
Interesting, that doesn't happen for me anymore (it did in the past, then I tried fixing it which seemed to work for me). What Enigma version is this?

**Comment by 2xsaiko** [comment]
Just did a terribly inaccurate (but hopefully at least somewhat representative) test of the CPU usage when searching (what I did was repeatedly enter common single/double letter combinations and then clear the search box again very quickly) vs. on startup. From this it looks like it uses an acceptable amount of CPU time (and looking at the process directly it never seems to use more than 50% of a single CPU core), and the UI stays responsive throughout.

So not sure what's going on here, either this is a "works on my machine" thing (tbh my CPU _is_ probably faster than most people's), you have an older version with a search that performs worse. Or there's some weird lockup going on because I can only modify the results list on the Swing thread which is not very nice. I could most likely reduce the amount of tasks submitted to the Swing task queue (right now that's one per search result that's supposed to be added to the list), but I have no idea if that will make a difference (especially since I can't test it myself).

![image](https://user-images.githubusercontent.com/3987560/116481418-6b575600-a883-11eb-9083-adc628ae2359.png)

**Comment by haykam821** [comment]
I can no longer reproduce this on version 0.27.1 with `./gradlew yarn`.

**Comment by haykam821** [comment]
I can still reproduce this issue with version 0.27.1 with `./gradle yarn`.

**Comment by liach** [comment]
See #282. Currently search does halt properly when you type a new character.

**Comment by haykam821** [comment]
I can confirm there's no longer any performance issues with search even when searching for single characters.

**Comment by liach** [comment]
Yeah, the only thing we need to do is to bump enigma in yarn later (I would prefer have enigma fix a few bugs and get to 1.3.3 before a bump)
