### ISSUE TITLE
Exporting Minecraft 1.18.1 Source Code Not Working

### ISSUE THREAD

**Issue by DarkBrave** [FabricMC/Enigma#439]
I'm using Enigma with Swing GUI to obfuscate and decompile Minecraft 1.18.1, and everything is going fine. I import the jar file and offical mappings perfectly, but when it comes to exporting the source code, I select a folder and it does nothing. From what I've seen, it's intended to work, but it just doesn't. I've tried a few different pre-compiled version of Enigma and even compiling it myself, but I still get this. There isn't any form of error message at all, it just doesn't do anything. I'm on Windows 10, but haven't tried it on my Linux instance yet.

**Comment by ryantheleach** [comment]
I'm in the same boat. Nothing else to add, just figured I'd let you know you arn't crazy @DarkBrave

**Comment by asdasdasdasdoof** [comment]
Yup, the same exact thing is happening to me.

**Comment by JAKCODING** [comment]
Same here.

**Comment by TheKodeToad** [comment]
Since Fabric doesn't use Enigma for decompilation - just for editing the obfuscation mappings, this is probably why this hasn't been fixed. I tried the same thing in 2020, and it didn't work then either (from what I can remember).

If you want to decompile the game, don't use Enigma. Use CFR (currently preferred by Fabric)  or Fernflower.

Also, I am (and was then) on Ubuntu, so it's not a Windows 10 thing.

**Comment by ryantheleach** [comment]
Personally I'm not looking for a perfect, compilable version of the game, nor do I believe Enigma ever intended on this decompile option to ever provide such. I just want to be able to conduct research from an IDE environment instead of Enigma occasionally when exploring.

**Comment by 2xsaiko** [comment]
> I just want to be able to conduct research from an IDE environment instead of Enigma occasionally when exploring and creating mappings.

Set up a normal Fabric dev environment (e.g. using the example mod), that will get you this.

**Comment by ryantheleach** [comment]
That makes some heavy assumptions about the mappings in use, instead of that which is currently loaded by Enigma.

**Comment by TheKodeToad** [comment]
If you want to grab mappings straight from the file, this is a method that I have used (sworn by) for some time.

Inside a folder, copy your mappings to a file named "client.txt".

Copy the client or server (it doesn't matter since the client mappings works with the server mappings, but not vice-versa) to "minecraft.jar".

In the same folder, run these commands (if you are on Windows, use WSL):
```
wget https://maven.fabricmc.net/cuchaz/enigma-cli/2.0.0/enigma-cli-2.0.0-all.jar -O enigma.jar
java -jar enigma.jar convert-mappings proguard client.txt tinyv2:obf:deobf client.tiny
wget https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1-fat.jar -O tiny.jar
java -jar tiny.jar minecraft.jar minecraft-deobf.jar client.tiny obf deobf
wget https://maven.fabricmc.net/net/fabricmc/cfr/0.0.9/cfr-0.0.9.jar -O cfr.jar
java -jar cfr.jar minecraft.jar --outputdir src
```

2xsaiko is right, and you'd probably be better off setting up a Fabric dev environment.

You can use the Mojang mappings by changing:
```
mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
```
to
```
mappings loom.officialMojangMappings()
```

**Comment by modmuss50** [comment]
This should now be fixed with: https://github.com/FabricMC/Enigma/commit/9f4e8979cb6d4059819833d932d4ead284bea1db and https://github.com/FabricMC/Enigma/commit/001dbed48c8ddfae879ab6cf594d3453cb3ce161
