### ISSUE TITLE
Duplicate Inherited Fields

### ISSUE THREAD

**Issue by darkhax** [FabricMC/Enigma#51]
It is currently possible for a class to have fields with the same name as a field in a parent class. This can lead to situations where methods within the class are accessing the newer fields rather than the ones inherited. Below are a few screenshots of where this can become an issue. 

![image](https://cloud.githubusercontent.com/assets/2250798/19595344/c712efd4-9746-11e6-821e-a9328084c334.png)
![image](https://cloud.githubusercontent.com/assets/2250798/19595333/b46d9faa-9746-11e6-9daf-1d9fa00f6543.png)

**Comment by asiekierka** [comment]
Unreverting my fix should be enough here...-------- Wiadomość oryginalna --------Temat: [FabricMC/Enigma] Duplicate Inherited Fields (#51)Od: Tyler Hancock Do: FabricMC/Enigma DW: It is currently possible for a class to have fields with the same name as a field in a parent class. This can lead to situations where methods within the class are accessing the newer fields rather than the ones inherited. Below are a few screenshots of where this can become an issue. 




—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FabricMC/Enigma","title":"FabricMC/Enigma","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FabricMC/Enigma"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Duplicate Inherited Fields (#51)"}],"action":{"name":"View Issue","url":"https://github.com/FabricMC/Enigma/issues/51"}}}
