### ISSUE TITLE
Mis-decompilations/ GOTOs in decompiled sources

### ISSUE THREAD

**Issue by Guigui220D** [FabricMC/Enigma#537]
In the resulting exported source I get things like : 

```java
if (!(aobj[i] instanceof String[])) ** GOTO lbl20
```

Which aren't Java code and I'm guessing the decompilation ends prematurely somewhere.

**Comment by 2xsaiko** [comment]
I don't think the decompilers make any guarantees about outputting valid Java source code. It's good enough in most cases (unless it completely gives up and outputs asm or crashes completely) since it's for reference while mapping only. This looks fine, but if the class is unreadable you can try switching the decompiler from the menu bar.

**Comment by modmuss50** [comment]
I agree, this isn't something for enigma to worry too much about.
