### ISSUE TITLE
Mapping format ProGuard not working correctly

### ISSUE THREAD

**Issue by derklaro** [FabricMC/Enigma#539]
I've written some code to decompile a minecraft client jar file using the official provided mojang mappings (at the time of writing it's client + client mapping 24w07a):
```java
    var enigma = Enigma.create();
    var project = enigma.openJar(this.inputJarFile, new ClasspathClassProvider(), PROGRESS_LISTENER);

    var idx = project.getJarIndex();
    var saveParameters = enigma.getProfile().getMappingSaveParameters();
    var mappingTree = MappingFormat.PROGUARD.read(this.mappingsPath, PROGRESS_LISTENER, saveParameters, idx);
    project.setMappings(mappingTree);

    var jarExport = project.exportRemappedJar(PROGRESS_LISTENER);
    jarExport.write(outputPath, PROGRESS_LISTENER);
 ```
 
 The exported jar from this method still has all classes obfuscated (same outcome with the Swing version):
![image](https://github.com/FabricMC/Enigma/assets/40468651/fee0558e-1667-4914-a45e-bb97f125537c)

However, when disabling the usage of mapping-io with `System.setProperty("enigma.use_mappingio", "false")` (or using the Proguard (Legacy) option in the Swing version), the code is deobfuscated correctly:
![image](https://github.com/FabricMC/Enigma/assets/40468651/704433aa-ff1c-4667-ac83-5c307bdc03df)

**Comment by NebelNidas** [comment]
Hmm, that's due to a disparity between the old reader and Mapping-IO's. The actual mapping file is `mojmap` -> `obfuscated`:
```
net.minecraft.BlockUtil -> l:
```
Mapping-IO parses this as-is, and since your JAR file is the other way around, nothing gets applied. Enigma's old reader only works because it always [inverts](<https://github.com/FabricMC/Enigma/blob/aaeff9a25ef6a916067dd10d21ee2df2eeb8f16e/enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/proguard/ProguardMappingsReader.java#L85>) the mappings for whatever reason, which is contrary to what you'd expect IMO.

@modmuss50 Should we make the new MIO reader behave like the existing Enigma reader or remove this behavior from the latter? I'd prefer not to auto-invert without prompting the user first.
